/* action > constant */

export const FETCH_WEIGHT_SUCCESS =  'FETCH_WEIGHT_SUCCESS'
export const FETCH_WEIGHT_LOADING =  'FETCH_WEIGHT_LOADING'
export const FETCH_WEIGHT_ERROR =  'FETCH_WEIGHT_ERROR'
export const ADD_WEIGHT_SUCCESS = 'ADD_WEIGHT_SUCCESS'
export const ADD_WEIGHT_LOADING = 'ADD_WEIGHT_LOADING'
export const ADD_WEIGHT_ERROR = 'ADD_WEIGHT_ERROR'
export const EDIT_WEIGHT_SUCCESS = 'EDIT_WEIGHT_SUCCESS'
export const EDIT_WEIGHT_LOADING = 'EDIT_WEIGHT_LOADING'
export const EDIT_WEIGHT_ERROR = 'EDIT_WEIGHT_ERROR'
export const DELETE_WEIGHT_SUCCESS = 'DELETE_WEIGHT_SUCCESS'
export const DELETE_WEIGHT_LOADING = 'DELETE_WEIGHT_LOADING'
export const DELETE_WEIGHT_ERROR = 'DELETE_WEIGHT_ERROR'

