/* action > constant */

export const FETCH_WEIGHT_SUCCESS =  'FETCH_WEIGHT_SUCCESS'
export const FETCH_WEIGHT_LOADING =  'FETCH_WEIGHT_LOADING'
export const FETCH_WEIGHT_ERROR =  'FETCH_WEIGHT_ERROR'
export const FETCH_ONE_WEIGHT_SUCCESS =  'FETCH_ONE_WEIGHT_SUCCESS'
export const FETCH_ONE_WEIGHT_LOADING =  'FETCH_ONE_WEIGHT_LOADING'
export const FETCH_ONE_WEIGHT_ERROR =  'FETCH_ONE_WEIGHT_ERROR'
export const ADD_WEIGHT_SUCCESS = 'ADD_WEIGHT_SUCCESS'
export const ADD_WEIGHT_LOADING = 'ADD_WEIGHT_LOADING'
export const ADD_WEIGHT_ERROR = 'ADD_WEIGHT_ERROR'
export const UPDATE_WEIGHT_SUCCESS = 'UPDATE_WEIGHT_SUCCESS'
export const UPDATE_WEIGHT_LOADING = 'UPDATE_WEIGHT_LOADING'
export const UPDATE_WEIGHT_ERROR = 'UPDATE_WEIGHT_ERROR'
export const DELETE_WEIGHT_SUCCESS = 'DELETE_WEIGHT_SUCCESS'
export const DELETE_WEIGHT_LOADING = 'DELETE_WEIGHT_LOADING'
export const DELETE_WEIGHT_ERROR = 'DELETE_WEIGHT_ERROR'

